# Generated by Django 3.1.1 on 2020-09-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200919_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
    ]
