# Generated by Django 2.2 on 2020-09-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20200921_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, upload_to='media/products/%Y/%m/%d'),
        ),
    ]
