# Generated by Django 2.2 on 2020-09-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20200921_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to='media/products/%Y/%m/%d', width_field='image_width'),
        ),
    ]
